### ISSUE TITLE
Use `pyproject.toml`

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf-zarr#5]
This project should be using a `pyproject.toml` file to specify its packaging metadata not a `setup.py` and `setup.cfg`.

Currently with `pip 23.0.1` the following warning:
```
DEPRECATION: asdf-zarr is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

While `pip 23.1+` does not technically require a `pyproject.toml` file, it is considered best practice to use it over `setup.py` and/or `setup.cfg`. PEP 621 lays out how to create a `pyproject.toml` file.

**Comment by braingram** [comment]
Fixed in #8
